name: Deploy Flask App

on:
  push:
    branches: [ "project1" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t flaskapp .

      - name: Deploy with docker-compose
        run: docker compose up -d
